spring:
  datasource:
    url: jdbc:h2:file:./data/studentdb;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;DB_CLOSE_DELAY=-1
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    initialization-mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
        trace: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update
      javax:
        persistence:
          schema-generation:
            database:
              action: update
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.JspServletWebServerFactoryAutoConfiguration
  sql:
    init:
      mode: always

server:
  port: 8080
  servlet:
    context-path: /

app:
  jwt:
    secret: your-jwt-secret-key-here-please-change-this-in-production
    expiration-ms: 86400000  # 24 hours
  finance-base-url: http://localhost:8081
  library-base-url: http://localhost:80

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.acme.studentportal: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
